config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "guest_orders#new"

  resources :guest_orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guest_order.rb
class GuestOrder < ApplicationRecord
    has_many :takoyaki_toppings, dependent: :destroy 
    has_many :takoyaki_topping_toppings, through: :takoyaki_toppings, source: :topping
end

app/models/takoyaki_topping.rb
class TakoyakiTopping < ApplicationRecord
  belongs_to :guest_order
  belongs_to :topping
  validates :guest_order_id, presence: true, uniqueness: { scope: :topping_id }
end

app/models/topping.rb
class Topping < ApplicationRecord
    has_many :takoyaki_toppings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guest_orders_controller.rb
class GuestOrdersController < ApplicationController
    def index
      @guest_orders = GuestOrder.all
    end

    def new 
      @guest_order = GuestOrder.new
    end

    def destroy
      @guest_order = GuestOrder.find(params[:id])
      @guest_order.destroy!
      redirect_to guest_orders_path, status: :see_other 
    end
  
    def create 
      @guest_order = GuestOrder.new(guest_order_params)
      @guest_order.total = 0
      calculate_order_total
      if @guest_order.save
        session[:guest_order_id] = @guest_order.id
        redirect_to guest_order_path(@guest_order)
      else
        flash.now['danger'] = '失敗しました'
        render :new
      end
    end

    def edit
      @guest_order = GuestOrder.find(params[:id])
    end

    def update
      @guest_order = GuestOrder.find(params[:id])
      if @guest_order.update(guest_order_params)
        session[:guest_order_id] = @guest_order.id
        redirect_to guest_order_path(@guest_order)
      else
        flash.now['danger'] = '失敗しました'
        render :new
      end
    end

    def show 
        @guest_order = GuestOrder.find(params[:id])
        @menu_items = {
            takoyaki_6s: 'たこ焼き6個入り',
            takoyaki_8s: 'たこ焼き8個入り',
            takoyaki_10s: 'たこ焼き10個入り',
            takoyaki_12s: 'たこ焼き12個入り',
            fried_takoyaki: 'あげたこ',
            cold_takoyaki: '冷凍たこ焼き',
            yakisoba: '焼きそば',
            yakisoba_1_half: '焼きそば1.5玉',
            yakisoba_egg: '焼きそば卵のせ',
            sobamesi: 'そば飯',
            beer: 'ビール',
            happoshu: '発泡酒'

        }
    end
  
    private
  
    def guest_order_params
      params.require(:guest_order).permit(
        :name, :takoyaki_6s, :takoyaki_8s, :takoyaki_10s, :takoyaki_12s,
        :fried_takoyaki, :cold_takoyaki, :yakisoba, :yakisoba_1_half,
        :yakisoba_egg, :sobamesi, :beer, :happoshu
      )
    end
  
    def calculate_order_total
      menu_items = {
        takoyaki_6s: 350, takoyaki_8s: 400, takoyaki_10s: 500, takoyaki_12s: 600,
        fried_takoyaki: 200, cold_takoyaki: 1500, yakisoba: 450, yakisoba_1_half: 500,
        yakisoba_egg: 500, sobamesi: 600, beer: 300, happoshu: 200
      }
  
      menu_items.each do |item, price|
        @guest_order.total += @guest_order.send(item).to_i * price
      end
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_orders_helper.rb
module GuestOrdersHelper
end

app/views/guest_orders/_form.html.erb
<%= form_with  model:guest_order, local: true do |f| %>
    <div class="form-group">
      <%= f.label :'名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <h2 class='text-primary'>たこ焼き</h2>
    <div class="form-group">
      <%= f.label :'たこ焼き6個入り(¥350)' %>
      <%= f.select :takoyaki_6s, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.takoyaki_6s), {}, class: 'form-control' %>
    </div> 
    <div class="form-group">
      <%= f.label :'たこ焼き8個入り(¥400)' %>
      <%= f.select :takoyaki_8s, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.takoyaki_8s), {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :'たこ焼き10個入り(¥500)' %>
        <%= f.select :takoyaki_10s, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.takoyaki_10s), {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :'たこ焼き12個入り(¥600)' %>
        <%= f.select :takoyaki_12s, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.takoyaki_12s), {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :'あげたこ(¥200)' %>
        <%= f.select :fried_takoyaki, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.fried_takoyaki), {}, class: 'form-control' %>
    </div> 
    <h2 class='text-danger'>冷凍たこ焼き</h2>
    <div class="form-group">
        <%= f.label :'冷凍たこ焼き(¥1500)' %>
        <%= f.select :cold_takoyaki, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.cold_takoyaki), {}, class: 'form-control' %>
    </div> 
    <h2 class='text-success'>焼きそば</h2>
    <div class="form-group">
        <%= f.label :'焼きそば(¥450)' %>
        <%= f.select :yakisoba, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.yakisoba), {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :'焼きそば1.5玉(¥500)' %>
        <%= f.select :yakisoba_1_half, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.yakisoba_1_half), {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :'焼きそば卵入り(¥500)' %>
        <%= f.select :yakisoba_egg, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.yakisoba_egg), {}, class: 'form-control' %>
    </div>
    <h2 class='text-warning'>そば飯</h2>
    <div class="form-group">
        <%= f.label :'そば飯(¥600)' %>
        <%= f.select :sobamesi, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.sobamesi), {}, class: 'form-control' %>
    </div>
    <h2 class='text-info'>飲み物</h2>
    <div class="form-group">
        <%= f.label :'ビール缶(¥300)' %>
        <%= f.select :beer, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.beer), {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :'発泡酒(¥200)' %>
        <%= f.select :happoshu, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], @guest_order.happoshu), {}, class: 'form-control' %>
    </div>
    <%= f.submit '注文作成', class: 'btn btn-primary' %>
<% end %>

app/views/guest_orders/_guest_order.html.erb
<div class="container mt-5">
  <div class="row">
    <% @guest_orders.each do |guest_order| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to guest_order.name, guest_order_path(guest_order), class: 'navbar-brand mb-0 h1 text-info'  %>様</h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/guest_orders/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>注文編集</h1>
      <%= render 'form', { guest_order: @guest_order} %>
    </div>
  </div>
</div>

app/views/guest_orders/index.html.erb
<div class="container mt-5">
  <div class="row">
   <h1>注文一覧</h1>
    <% @guest_orders.each do |guest_order| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to guest_order.name, guest_order_path(guest_order), class: 'navbar-brand mb-0 h1 text-info'  %>様</h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/guest_orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>注文</h1>
     <%= render 'form', { guest_order: @guest_order} %>
    </div>
  </div>
</div>

app/views/guest_orders/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-9'>
            <%= link_to '編集', edit_guest_order_path(@guest_order), class: 'btn btn-success' %>
            <%= link_to '過去注文一覧', guest_orders_path, class: 'btn btn-success' %>
            <%= link_to '削除', guest_order_path(@guest_order), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
              <h3><%=@guest_order.name%>様</h3>
              <h2 class="text-primary">¥<%=@guest_order.total%>円</h2>
            </div>
          </div>
          <% @menu_items.each do |item, label| %>
            <% unless @guest_order.send(item) == "0" %>
              <h4 class="pt-5"><%= label %></h4>
              <%= @guest_order.send(item) %>個
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Order</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>